version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  frontend:
    labels:
      - traefik.backend=juandastic
      - traefik.frontend.rule=Host:juandastic.co
      - traefik.docker.network=proxy
      - traefik.port=3000
    networks:
      - internal
      - proxy